version: "3.1"
services:
  mysql-db:
    image: mysql:8.0.17
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rs-database
    ports:
      - "3308:3306"
